server:
  port: 8763

eureka:
  instance:
    hostname: peer3
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  server:
    enable-self-preservation: false   # 关闭自我保护机制，正常情况不推荐使用，用于测试查看关闭其他服务时在注册列表中剔除

spring:
  application:
    name: eureka-server
