

spring:
  application:
    name: eureka-feign-client  # 应用名称
#  main:
#    allow-bean-definition-overriding: true  # 设置可以定义重复的bean

server:
  port: 8767      # 端口

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # 服务注册地址

feign:
  hystrix:
    enabled: true   # 文件中没有提示，不影响

