spring:
  application:
    name: service-turbine

server:
  port: 8768

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

turbine:
  instanceUrlSuffix: /hystrix.stream  # instanceUrlSuffix 访问前缀默认为/actuator/hystrix.stream
  aggregator:
    cluster-config: default     #  指定聚合哪些集群,多个使用","分割，默认为default
  app-config: eureka-ribbon-client-1,eureka-feign-client # 配置监控服务的列表，表明监控哪些服务多个使用","分割
#or
  cluster-name-expression: new String("default")  # 集群名称默认为服务名的集群，当服务数量非常多的时候，可以启动多个
  combine-host-port: true
#  turbine.combine-host-port参数设置为true，可以让同一主机上的服务通过主机名与端口号的组合来进行区分，默认情况下会以host来区分不同的服务，这会使得在本机调试的时候，本机上的不同服务聚合成一个服务来统计。




